### ISSUE TITLE
Invalid value for --neg-ref-db-fp

### ISSUE THREAD

**Issue by mortonjt** [biocore/deblur#101]
Traceback (most recent call last):
  File "/home/mortonjt/miniconda/envs/deblur/bin/deblur", line 659, in <module>
    deblur_cmds()
  File "/home/mortonjt/miniconda/envs/deblur/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mortonjt/miniconda/envs/deblur/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python3.5/site-packages/click/core.py", line 86, in augment_usage_errors
    yield
  File "/home/mortonjt/miniconda/envs/deblur/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mortonjt/miniconda/envs/deblur/bin/deblur", line 622, in workflow
    neg_ref_db_fp, jobs_to_start)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python3.5/site-packages/deblur/parallel_deblur.py", line 142, in parallel_deblur
    es))
RuntimeError: stdout: 
stderr: Usage: deblur workflow [OPTIONS]

Error: Invalid value for "--neg-ref-db-fp": Path "" is not readable.

exit: 2

**Comment by mortonjt** [comment]
Any idea what is going on?

**Comment by wasade** [comment]
That looks like either a malformed commandline or a bad path. Do you know if this is still an issue? If not, please close.

**Comment by wasade** [comment]
No response on this, so closing
