### ISSUE TITLE
Variable referenced before assignment

### ISSUE THREAD

**Issue by wasade** [biocore/deblur#117]
[here](https://github.com/biocore/deblur/blob/master/scripts/deblur#L616)

```python
Traceback (most recent call last):
  File "/home/mcdonadt/miniconda3/envs/deblur/bin/deblur", line 664, in <module>
    deblur_cmds()
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mcdonadt/miniconda3/envs/deblur/bin/deblur", line 618, in workflow
    if deblurred_file_name is None:
UnboundLocalError: local variable 'deblurred_file_name' referenced before assignment

```

**Comment by wasade** [comment]
This is still an issue, new line is [here](https://github.com/biocore/deblur/blob/master/scripts/deblur#L613).

**Comment by amnona** [comment]
? is this fixed or not? what does the new line mean?

**Comment by wasade** [comment]
The referenced hyperlink points to a specific line of code in which there is an undefined variable.

**Comment by amnona** [comment]
fixed.
