### ISSUE TITLE
convert float to int

### ISSUE THREAD

**Issue by jtremblay** [biocore/deblur#172]
Dear deblur developers,
I got this error when trying to run this command:
I believe it can be sovled with adding an int(<float>)

```
deblur workflow --seqs-fp ./infiles/ --output-dir ./deblur_outdir/  --overwrite -t 100 
/gc/software/miniconda/miniconda-2/envs/deblurenv/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In fu
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/bin/deblur", line 684, in <module>
    deblur_cmds()
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/bin/deblur", line 655, in workflow
    outputfasta_fp=outputfasta_fp, minreads=min_reads)
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/lib/python3.5/site-packages/deblur/workflow.py", line 706, in create_otu_table
    obs = scipy.sparse.dok_matrix((1E9, len(deblurred_list)), dtype=np.double)
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/lib/python3.5/site-packages/scipy/sparse/dok.py", line 88, in __init__
    self._shape = check_shape((M, N)) 
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/lib/python3.5/site-packages/scipy/sparse/sputils.py", line 281, in check_shape
    new_shape = tuple(operator.index(arg) for arg in args)
  File "/gc/software/miniconda/miniconda-2/envs/deblurenv/lib/python3.5/site-packages/scipy/sparse/sputils.py", line 281, in <genexpr>
    new_shape = tuple(operator.index(arg) for arg in args)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by olsonca** [comment]
Hello,

I have the same issue, has anyone been able to help with this? Here is my error message: 
<img width="567" alt="error" src="https://user-images.githubusercontent.com/39746283/40684531-700c327c-6346-11e8-81c8-721cd1d11af1.png">

Best,
Christine

**Comment by gsmashd** [comment]
Same issue here. In line 705 in deblur/workflow.py, change 

`obs = scipy.sparse.dok_matrix((1E9, len(deblurred_list)), dtype=np.double)`
to
`obs = scipy.sparse.dok_matrix((int(1E9), len(deblurred_list)), dtype=np.double)`

`1E9` is evaluated as 1000000000.0 rather than 1000000000. Hence, it must be cast as an int.
