### ISSUE TITLE
Failure to write BIOM file - OSError: Unable to create file

### ISSUE THREAD

**Issue by feargalr** [biocore/deblur#175]
Hi, 

I'm getting the following error which results deblur failing. I installed via conda. All intermediate files are created and look good to me at least. 

Any tips/advice?

Thanks!

Traceback (most recent call last):
  File "/homes/user1/anaconda2/envs/deblurenv/bin/deblur", line 684, in <module>
    deblur_cmds()
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/homes/user1/anaconda2/envs/deblurenv/bin/deblur", line 655, in workflow
    outputfasta_fp=outputfasta_fp, minreads=min_reads)
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/site-packages/deblur/workflow.py", line 767, in create_otu_table
    write_biom_table(table, output_fp)
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/site-packages/deblur/workflow.py", line 638, in write_biom_table
    with biom_open(biom_fp, 'w') as f:
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/site-packages/biom/util.py", line 465, in biom_open
    f = opener(fp, mode)
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/homes/user1/anaconda2/envs/deblurenv/lib/python3.5/site-packages/h5py/_hl/files.py", line 148, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to lock file, errno = 37, error message = 'No locks available')

**Comment by wasade** [comment]
Hi @feargalr, I apologize for the delay in a response on this issue. It appears the problem is upstream of Deblur and potentially a problem with your server -- I'm assuming you're using an NFS mount? See [here](https://github.com/h5py/h5py/issues/1082#issuecomment-414291188) for a possible fix.

Please reopen if the suggestion in the comment doesn't work.
