### ISSUE TITLE
bug Mac, error message

### ISSUE THREAD

**Issue by rderelle** [biocore/deblur#190]
Hi,

I'm getting an error message when trying to use Deblur to denoise multiple fasta files on a Mac laptop.

My command line is:
deblur workflow --seqs-fp all_fasta.fas --output-dir aaa -t 150

The file all_fasta.fas contains all fasta sequences in qiime2 format. Delblur successfully splits the file into samples, denoise each sample but fails at the end to generate the biom file. 

The error message in my terminal is:
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/bin/deblur", line 684, in <module>
    deblur_cmds()
  File "/Users/xxx/miniconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxx/miniconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/xxx/miniconda3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxx/miniconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxx/miniconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/xxx/miniconda3/bin/deblur", line 655, in workflow
    outputfasta_fp=outputfasta_fp, minreads=min_reads)
  File "/Users/xxx/miniconda3/lib/python3.5/site-packages/deblur/workflow.py", line 705, in create_otu_table
    obs = scipy.sparse.dok_matrix((1E9, len(deblurred_list)), dtype=np.double)
  File "/Users/xxx/miniconda3/lib/python3.5/site-packages/scipy/sparse/dok.py", line 88, in __init__
    self._shape = check_shape((M, N))
  File "/Users/xxx/miniconda3/lib/python3.5/site-packages/scipy/sparse/sputils.py", line 281, in check_shape
    new_shape = tuple(operator.index(arg) for arg in args)
  File "/Users/xxx/miniconda3/lib/python3.5/site-packages/scipy/sparse/sputils.py", line 281, in <genexpr>
    new_shape = tuple(operator.index(arg) for arg in args)
TypeError: 'float' object cannot be interpreted as an integer

Do you know what could be wrong (with my data or my Deblur installation) ?

many thanks
Romain

**Comment by wasade** [comment]
Hi @rderelle, this issue was fixed in the recent Deblur v1.1.0 release
