### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by mortonjt** [biocore/deblur#39]
I'm getting a weird error when I tried to run the deblur workflow.

I'm running the following command

```
deblur workflow \
  --seqs-fp 648_seqs.fasta \
  --output-dir deblurred \
  --ref-fp /home/mortonjt/deblur_db/artifacts.fa \
  -n -w -d 1,0.06,0.02,0.02,0.01,0.005,0.005,0.005,0.001,0.001,0.001,0.0005 \
  -t 150 -O 32 \
  --log-level 2 \
  --log-file log.newmonkies.neg \
  --min-reads 25
```
And I get the following error
```
discarding /home/mortonjt/miniconda/bin from PATH
prepending /home/mortonjt/miniconda/envs/deblur/bin to PATH
Traceback (most recent call last):
  File "/home/mortonjt/miniconda/envs/deblur/bin/deblur", line 572, in <module>
    deblur_cmds()
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mortonjt/miniconda/envs/deblur/bin/deblur", line 543, in workflow
    parallel_deblur(input_file_list, sys.argv, ref_db_fp, jobs_to_start)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/deblur/parallel_deblur.py", line 130, in parallel_deblur
    es))
RuntimeError: stdout: 
stderr: Traceback (most recent call last):
  File "/home/mortonjt/miniconda/envs/deblur/bin/deblur", line 572, in <module>
    deblur_cmds()
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mortonjt/miniconda/envs/deblur/bin/deblur", line 535, in workflow
    delim=delim)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/deblur/workflow.py", line 570, in launch_workflow
    min_size=min_size, threads=threads_per_sample)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/deblur/workflow.py", line 82, in dereplicate_seqs
    sout, serr, res = _system_call(params)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/site-packages/deblur/workflow.py", line 679, in _system_call
    stderr=subprocess.PIPE)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/mortonjt/miniconda/envs/deblur/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

exit: 1
```
The last few steps in `log.newmonkies.neg` was as follows
```
FO(139964386215680)2016-08-09 13:19:46,210:launch_workflow for file /home/mortonjt/Documents/potato_16S/data/illumina_reads/deblurred/split/1706.F54.7.prev.fasta
INFO(140568600663808)2016-08-09 13:19:46,315:dereplicate seqs file /home/mortonjt/Documents/potato_16S/data/illumina_reads/deblurred/deblur_working_dir/1706.F51.0.prev.fasta.trim
INFO(139964386215680)2016-08-09 13:19:46,732:dereplicate seqs file /home/mortonjt/Documents/potato_16S/data/illumina_reads/deblurred/deblur_working_dir/1706.F54.7.prev.fasta.trim
INFO(140204884723456)2016-08-09 13:19:46,739:dereplicate seqs file /home/mortonjt/Documents/potato_16S/data/illumina_reads/deblurred/deblur_working_dir/1706.F6.2.prev.fasta.trim
```
I'm not exactly sure what is going on.  Any ideas about how I can start debugging this?  Thanks!

**Comment by ekopylova** [comment]
Hmm ... this looks like that multithreading error I was receiving in my original [parallel PR](https://github.com/biocore/deblur/pull/33). @amnona mentioned he wasn't seeing the error any longer with his version (now merged into master). From my experience, the trimmed reads were not being written to a file (when using multithreading) and the resulting empty file caused failures in downstream analyses. I would suggest looking at [these lines](https://github.com/biocore/deblur/blob/master/deblur/workflow.py#L561) and determine why nothing is being written out to file even though trimming appears to be working correctly.

**Comment by amnona** [comment]
Strange...
Didn't encounter the mutithreading error on local mac/barnacle/travis...
Anyway, can try to look at the log ("log.newmonkies.neg") file to see
exactly what's going on
Jamie - let me know when u have time. And thanks!!!!


On Thu, Aug 11, 2016 at 9:53 AM, Evguenia Kopylova <notifications@github.com

**Comment by josenavas** [comment]
This error shows up when there is a missing dependency. Burrito-fillings was providing a useful error while the current implementation does not...

**Comment by amnona** [comment]
Aha!
seems like the problem is that the trim length (-t) is 150bp, whereas the
sequence length is only 100?
(guess we need to add a warning if the trim length is longer than the vast
majority of the sequences :)    )
Does this make sense? can you rerun it with -t 100 ?

**Comment by wasade** [comment]
@mortonjt, were you able to verify the trim length as the issue here?

**Comment by mortonjt** [comment]
This was a result of some dependency issues from not installing sortmerna or vsearch.
