### ISSUE TITLE
BUG : too many open files when splitting on mac

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#77]
Got this from a user:
ANOTHER ERROR ( ONLY solution seems to be to divide the file up into pieces)

(deblurenv)MacQIIME dhcp238­043:~ $ deblur workflow ­­seqs­fp

/Volumes/Samsung_T1/MadaRaw/Mada_AS13JF14ND14_Splitlib_r3n0p.90q5/Mada_AS13JF14ND14_Splitlib_r3n0p.90q5_seqs250_254new.fasta

­­output­dir Madajul16_deblurtest ­O 3

Traceback (most recent call last):

File "/macqiime/anaconda/envs/deblurenv/bin/deblur", line 621, in <module>

deblur_cmds()

File "/macqiime/anaconda/envs/deblurenv/lib/python3.5/site­packages/click/core.py", line 716, in __call__

return self.main(*args, **kwargs)

File "/macqiime/anaconda/envs/deblurenv/lib/python3.5/site­packages/click/core.py", line 696, in main

rv = self.invoke(ctx)

File "/macqiime/anaconda/envs/deblurenv/lib/python3.5/site­packages/click/core.py", line 1060, in invoke

return _process_result(sub_ctx.command.invoke(sub_ctx))

File "/macqiime/anaconda/envs/deblurenv/lib/python3.5/site­packages/click/core.py", line 889, in invoke

return ctx.invoke(self.callback, **ctx.params)

File "/macqiime/anaconda/envs/deblurenv/lib/python3.5/site­packages/click/core.py", line 534, in invoke

return callback(*args, **kwargs)

File "/macqiime/anaconda/envs/deblurenv/bin/deblur", line 561, in workflow

out_dir_split)

File "/macqiime/anaconda/envs/deblurenv/lib/python3.5/site­packages/deblur/workflow.py", line 445, in

split_sequence_file_on_sample_ids_to_files

outputs[sample] = open(join(outdir, sample + '.fasta'), 'w')

OSError: [Errno 24] Too many open files: '/Users/venceslab/Madajul16_deblurtest/split/J8.3.fasta'

**Comment by wasade** [comment]
Or a smarter algorithm for partitioning a single fasta file in which fewer handles are open at a time. Probably could be done with a heap where the files which haven't been written too recently get closed, and reopened if needed

**Comment by josenavas** [comment]
Probably using a "pool" of file handles that we open/close as needed.

**Comment by wasade** [comment]
This still appears to be an issue. @amnona is there a trajectory toward a resolution here?

Note: this is _not_ an issue when driven from qiime2, and so one strategy we can undertake is just actively recommend users leverage the plugin.

**Comment by amnona** [comment]
i think this will be left for version 2. currently mac users can split using qiime or qiime2?

**Comment by wasade** [comment]
Please note in the README

**Comment by amnona** [comment]
added in troubleshooting section
