### ISSUE TITLE
deblur from pip fails

### ISSUE THREAD

**Issue by wasade** [biocore/deblur#82]
I performed a pip install of deblur (`pip install deblur`) today and received the following traceback from a test run:

``` python
Traceback (most recent call last):
  File "/home/mcdonadt/miniconda3/envs/deblur/bin/deblur", line 621, in <module>
    deblur_cmds()
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 86, in augment_usage_errors
    yield
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mcdonadt/miniconda3/envs/deblur/bin/deblur", line 570, in workflow
    working_dir=working_dir)
  File "/home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/deblur/workflow.py", line 199, in build_index_sortmerna
    raise RuntimeError('Cannot index database file %s' % db)
RuntimeError: Cannot index database file /home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/deblur/support_files/artifacts.fa
```

**Comment by wasade** [comment]
The file does exist so unsure of the issue at this time:

```bash
$ ls /home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/deblur/support_files/artifacts.fa
-rw-r--r-- 1 dtmcdonald knightlab 17K Oct  3 16:09 /home/mcdonadt/miniconda3/envs/deblur/lib/python3.5/site-packages/deblur/support_files/artifacts.fa
```

**Comment by wasade** [comment]
Log file:

```bash
indexdb_rna: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by indexdb_rna)
```

**Comment by wasade** [comment]
Closing as I believe this was resolved through fixes to the builds.
